### ISSUE TITLE
[ERROR] addons/rdm_refunder-master/lua/autorun/client/cl_rdm.lua:109: attempt to index global 'ply' (a nil value)   1. DoClick - addons/rdm_refunder-master/lua/autorun/client/cl_rdm.lua:109    2. unknown - lua/vgui/dlabel.lua:218

### ISSUE THREAD

**Issue by magnus505** [Vloxan/rdm_refunder#1]
I change the Command and i get this error using m9k

[ERROR] addons/rdm_refunder-master/lua/autorun/client/cl_rdm.lua:109: attempt to index global 'ply' (a nil value)
  1. DoClick - addons/rdm_refunder-master/lua/autorun/client/cl_rdm.lua:109
   2. unknown - lua/vgui/dlabel.lua:218

**Comment by Vloxan** [comment]
I believe you're running an outdated version. Update and let me know how it
goes.

**Comment by magnus505** [comment]
I can't bee running on a old version i downladoed The addons yesterday

**Comment by Vloxan** [comment]
What do you mean you change the command and get this error? Please be more specific.

**Comment by Vloxan** [comment]
Seems like this is a bug on my part, one moment while I fix it.

**Comment by Vloxan** [comment]
Should be fixed now, make a new issue if the issue persists.
